### ISSUE TITLE
[FEATURE] Add ability to toggle a powder chest solver to only work when staring on a chest

### ISSUE THREAD

**Issue by fredster5** [RoseGoldIsntGay/GumTuneClient#7]
Self explanatory, it makes it look more legit
It's kinda suspicious when you are solving the chest and shit gets mined beside you
idk I would love to hear your opinion about it
also first issue yay

**Comment by RoseGoldIsntGay** [comment]
will be added

also, dont use this as a way to suggest features. join the discord to suggesti

**Comment by fredster5** [comment]
Understood 🫡 ty
